title: Jane's Hello World
email: janezhu918@gmail.com
description: I love coding ❤️
baseurl: "jane"
url: ""
twitter_username: jw8zhu
github_username:  janezhu1618

# Build settings
theme: jekyll-theme-merlot
plugins:
  - jekyll-feed

defaults:
  - scope:
      path: "assets/images"
      values:
        image: true
